name: CI

on:
  push:
    branches:
      - master
    tags:
      - '[0-9].[0-9]+.[0-9]+'
  release:
    types: [published]
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Mock Checkout
        run: |
          echo "checkout happens here"
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Mock testing
        run: |
          echo "${{ toJSON(github)}}"
  testpublish:
    name: Build test Distribution
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: First Step
      run: |
        echo "repos: ${{ github.repository }} ${{ github.event.pull_request.head.repo.full_name }}"
        echo "event ref: ${{ github.event.ref }}"
    - name: Second Step
      run: |
        echo "Conditionally echo ${{ secrets.MY_SECRET }}"
  publish:
    name: Build Real Distribution
    if: github.event_name == 'release' &&
      github.event.release.target_commitish == 'master' &&
      startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: First Step
      run: |
        echo "target: ${{ github.event.release.target_commitish }}"
        echo "event ref: ${{ github.ref }}"
        echo "tag: ${{ github.event.release.tag_name }}"
        echo "event name: ${{ github.event_name }}"
        echo "full event: ${{ toJSON(github)}}"
    - name: Second Step
      run: |
        echo "Conditionally echo ${{ secrets.MY_SECRET }}"
