name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo head_ref is "${{ github.head_ref }}"
        echo base_ref is "${{ github.base_ref }}"
    - name: Run if present
      if: secrets
      run: |
        echo ${{ github.event }}
