name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo repository is "${{ github.repository }}"
        echo actor is "${{ github.actor }}"
        echo ref is "${{ github.ref }}"
        echo head_ref is "${{ github.head_ref }}"
        echo base_ref is "${{ github.base_ref }}"
        echo event is "${{ github.event }}"
        echo "${{ github.event.pull_request.url }}"
        echo "${{ github.event.pull_request.fork }}"
    - name: Run if false
      if: github.event.pull_request.fork == false
      run: |
        echo in local pull request.
    - name: Run if true
      if: github.event.pull_request.fork == true
      run: |
        echo in forked pull request.
