name: CI

on:
  push:
    branches:
      - master
    tags:
      - '[0-9].[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Mock Checkout
        run: |
          echo "checkout happens here"
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Mock Test
        run: |
          echo "testing happens here"
  testpublish:
    name: Build test Distribution
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: First Step
      run: echo "This is the first step"
    - name: Second Step (Conditional)
      if: github.event.pull_request.head.repo.full_name == github.repository
      run: |
        echo "Conditionally echo ${{ secrets.MY_SECRET }}"
  publish:
    name: Build test Distribution
    runs-on: ubuntu-latest
    needs: testpublish
    steps:
    - name: First Step
      run: echo "This is the first step"
    - name: Second Step (Conditional)
      if: github.ref == 'refs/heads/master' && startsWith(github.event.ref, 'refs/tags')
      run: |
        echo "Conditionally echo ${{ secrets.MY_SECRET }}"
