name: CI

on:
  push:
    branches:
      - master
  release:
    types: [published]
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Mock Checkout
        run: |
          echo "checkout happens here"
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Mock testing
        run: |
          echo "${{ toJSON(github)}}"
  testpublish:
    name: Build test Distribution
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: First Step
      run: |
        echo "repos: ${{ github.repository }} ${{ github.event.pull_request.head.repo.full_name }}"
        echo "event ref: ${{ github.event.ref }}"
    - name: Second Step
      run: |
        echo "Conditionally echo ${{ secrets.MY_SECRET }}"
  publish:
    name: Build Real Distribution
    if: github.event == 'release' && github.event.base_ref == 'refs/heads/master' && startsWith(github.event.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: First Step
      run: |
        echo "base ref: ${{ github.event.base_ref }}"
        echo "event ref: ${{ github.event.ref }}"
    - name: Second Step
      run: |
        echo "Conditionally echo ${{ secrets.MY_SECRET }}"
