name: CI

on:
  release:
    types: [published]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Dump full github object
        run: |
          echo "${{ toJSON(github) }}"
